[build-wasm]
canister = "ICMLPSample"
did_path = "src/ICMLPSample.did"
cpp_paths = [
	"af_forge/include/fg/*.h",
	"af_glad/include/glad/*.h",
	"af_glad/include/KHR/*.h",
	"af_glad/src/*.c",
	"arrayfire/*/*/*.hpp",
	"arrayfire/*/*/*/*.cpp",
	"arrayfire/*/*/*/*.hpp",
	"arrayfire/*/*/*/*/*.cpp",
	"arrayfire/*/*/*/*/*.hpp",
	"arrayfire/*/*/*/*/*/*.cpp",
	"arrayfire/*/*/*/*/*/*.hpp",
	"arrayfire/*/*/*/*/*/*/*.cpp",
	"arrayfire/*/*/*/*/*/*/*.hpp",
	"boost/*.hpp",
	"boost/*/*.hpp",
	"boost/*/*/*.hpp",
	"boost/*/*/*/*.hpp",
	"cereal/*.hpp",
	"cereal/*/*.hpp",
	"cereal/*/*/*.hpp",
	"cereal/*/*/*/*.hpp",
	"fftw/api/*.h",
	"fftw/api/*.c",
	"fftw/dft/*.h",
	"fftw/dft/*.c",
	"fftw/dft/scalar/*.h",
	"fftw/dft/scalar/*.c",
	"fftw/dft/scalar/codelets/*.h",
	"fftw/dft/scalar/codelets/*.c",
	"fftw/kernal/*.c",
	"fftw/rdft/*.h",
	"fftw/rdft/*.c",
	"fftw/rdft/scalar/*.h",
	"fftw/rdft/scalar/*.c",
	"fftw/rdft/scalar/*/*.h",
	"fftw/rdft/scalar/*/*.c",
	"fftw/reodft/*.h",
	"fftw/reodft/*.c",
	"fftw/threads/*.h",
	"fftw/threads/*.c",
	]
cpp_include_dirs = [
	"af_forge/include/",
	"arrayfire/include/",
	]
cpp_compile_flags = ["-D JSON_HAS_FILESYSTEM=0"]
cpp_link_flags = []
c_paths = []
c_include_dirs = []
c_compile_flags = []
[build-native]
cpp_paths = ["native/main.cpp"]
cpp_include_dirs = []
cpp_compile_flags = []
cpp_link_flags = []
c_paths = []
c_include_dirs = []
c_compile_flags = []
